name: Build Test

on:
  pull_request:
    branches:
      - jekyll

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get install libtidy-dev
          bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake test
      - name: Gen page
        run: bundle exec rake build
      - name: Validate
        run: bundle exec rake validate_markup
