name: Deploy

on:
  push:
    branches:
      - jekyll

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get install libtidy-dev
          bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake test
      - name: Gen page
        run: bundle exec rake build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
